export const ATOR_FETCH_REQUEST = 'ATOR_FETCH_REQUEST';
export const ATOR_FETCH_SUCCESS = 'ATOR_FETCH_SUCCESS';

export const CONTEUDO_FETCH_REQUEST = 'CONTEUDO_FETCH_REQUEST';
export const CONTEUDO_FETCH_SUCCESS = 'CONTEUDO_FETCH_SUCCESS';
export const CONTEUDO_PLAY = 'CONTEUDO_PLAY';

export const USUARIO_FETCH_REQUEST = 'USUARIO_FETCH_REQUEST';
export const USUARIO_FETCH_SUCCESS = 'USUARIO_FETCH_SUCCESS';
export const USUARIO_EDITAR_PERFIL = 'USUARIO_EDITAR_PERFIL';
export const USUARIO_ADICIONAR_DEPENDENTE = 'USUARIO_ADICIONAR_DEPENDENTE';
